#!/bin/bash

# rust gems
cargo install --list | grep '^[a-zA-Z0-9_\-]* v[0-9.]*:$' | cut -d ' ' -f1 | xargs cargo install

# python
#python3 -m pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo python3 -m pip install -U
python3 -m pip install -r <(pip freeze) --upgrade

# go bins
go get -u all
