#!/bin/bash

dark () {
	# set gtk theme
	sed -i 's/gtk-theme-name=Breeze/gtk-theme-name=Breeze-Dark/g' $HOME/.config/gtk-3.0/settings.ini

	# set rofi theme
	sed -i 's/light/dark/g' $HOME/.config/rofi/config.rasi

	# set terminal theme
	sed -i 's/*light/*dark/g' $HOME/.config/alacritty/alacritty.yml

	#set batcat theme
	sed -i 's/gruvbox-light/gruvbox-dark/g' $HOME/.config/bat/config
}

light () { 
	# set gtk theme
	sed -i 's/gtk-theme-name=Breeze-Dark/gtk-theme-name=Breeze/g' $HOME/.config/gtk-3.0/settings.ini

	# set rofi theme
	sed -i 's/dark/light/g' $HOME/.config/rofi/config.rasi
	
	# set terminal theme
	sed -i 's/*dark/*light/g' $HOME/.config/alacritty/alacritty.yml

	# set batcat theme
	sed -i 's/gruvbox-dark/gruvbox-light/g' $HOME/.config/bat/config
}

# load theme
if grep -q -i "gtk-theme-name=Breeze-Dark" $HOME/.config/gtk-3.0/settings.ini; then
	light
else
	dark
fi

# check if firefox is running
f_run=$(ps -e | grep "firefox")
if [ $? -eq 0 ] ; then
	killall firefox; i3-msg 'workspace 2; exec firefox'
fi




