#!/bin/sh

# apt
sudo apt update
sudo apt dist-upgrade -y
sudo apt autoclean -y
sudo apt autoremove -y

# snap
sudo snap refresh

# flatpak
sudo flatpak update -y

# gits
ls $HOME/tools/ | xargs -P10 -I{} git -C $HOME/tools/{} pull

